---
title: "Index"
output: html_document
---


```{r message=FALSE, error=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```
## New York Presidential Results

```{r message=FALSE, error=FALSE}
county_poll = read_excel("./data/nycounty_results.xlsx") %>%
  janitor::clean_names() %>%
  mutate(
    election_result = ifelse(biden_pct > 0.5, "D", "R") #D stands for Democratic party win and R stands for Republican Party win
  ) %>%
  separate(county, c("county", "drop")) %>% 
  select(county, election_result)

county_poll
```

## New York Statewide Covid-19 Testing

```{r message=FALSE, error=FALSE}
testing_df = read_csv("./data/New_York_State_Statewide_COVID-19_Testing.csv") %>%
  janitor::clean_names() %>%
  transform(test_date = as.Date(test_date, "%m/%d/%y"))
```

Monthly infection rate at Albany county
```{r}
testing_df_albany = testing_df %>%
  filter(county == "Albany") %>% 
  group_by(month = floor_date(test_date, "month")) %>%
  summarise(
    monthly_new_positives = sum(new_positives),
    monthly_new_tests_performed = sum(total_number_of_tests_performed),
    monthly_infection_rate = monthly_new_positives/monthly_new_tests_performed
    )
```
write a function which takes county_name and returns the monthly infection rate for that county
```{r}
monthly_infection_rate = function(county_name){
  infection_rate_df = testing_df %>%
  filter(county == county_name) %>% 
  group_by(month = floor_date(test_date, "month")) %>%
  summarise(
    monthly_new_positives = sum(new_positives),
    monthly_new_tests_performed = sum(total_number_of_tests_performed),
    monthly_infection_rate = monthly_new_positives/monthly_new_tests_performed
    )
  infection_rate_df
}

monthly_infection_rate("Broome")
```
```{r}
counties_ny = testing_df %>%
  pull(county) %>%
  unique()

infection_rate_results = 
  tibble(
    county = counties_ny
  ) %>% 
  mutate(
    output_lists = map(.x = county, ~ monthly_infection_rate(.x)),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)

infection_rate_results

infection_rate_results %>%
  ggplot(aes(month, monthly_infection_rate, color = county)) +
  geom_line()
```

```{r}
fatality_rate_results =
  read_csv("./data/ny_state_bymonth_testpopmor.csv") %>%
  janitor::clean_names() %>%
  select(c(month, county, month_fatal)) %>%
  mutate(month = recode(
    month,
    "March" = "2020-03-01",
    "April" = "2020-04-01",
    "May" = "2020-05-01",
    "June" = "2020-06-01",
    "July" = "2020-07-01",
    "August" = "2020-08-01",
    "September" = "2020-09-01",
    "October" = "2020-10-01",
    "November" = "2020-11-01"
  )) %>%
  transform(month = as.Date(month)) %>%
  arrange(county, month)

merged_df = left_join(infection_rate_results, fatality_rate_results, by = c("county","month")) %>%
  rename(monthly_fatality_rate = month_fatal)

write.csv(merged_df, file = "merged_df.csv", quote = FALSE, row.names = F) 
```


-----------------------------------

## New York Covid-19 Nursing home data

```{r message=FALSE, error=FALSE}
nh_df = read_csv("./data/COVID-19 Nursing Home Data - Archived Data - Week Ending 10_25_20.csv") %>%
  janitor::clean_names() %>%
  filter(provider_state == "NY") %>%
  select(c(
    week_ending,
    provider_name,
    residents_weekly_admissions_covid_19,
    residents_total_admissions_covid_19,
    residents_weekly_confirmed_covid_19,
    residents_total_confirmed_covid_19,
    residents_weekly_all_deaths,
    residents_total_all_deaths,
    residents_weekly_covid_19_deaths,
    residents_total_covid_19_deaths,
    number_of_all_beds,
    total_number_of_occupied_beds,
    staff_weekly_confirmed_covid_19,
    staff_total_confirmed_covid_19,
    ventilator_dependent_unit,
    total_resident_confirmed_covid_19_cases_per_1_000_residents,
    total_resident_covid_19_deaths_per_1_000_residents,
    county
    ))
```
## Merge election data onto nursing home data

```{r}
merged_df = left_join(nh_df, county_poll, by = "county")

head(merged_df)
```


